### ISSUE TITLE
pytorch

### ISSUE THREAD

**Issue by GF1447571253** [alexandrosstergiou/adaPool#3]
can adapool function completely implement in torch，without any cpp

**Comment by alexandrosstergiou** [comment]
Hi @GF1447571253,

There are no plans currently to have a pure pytorch implementation. Mainly because of the computational and memory requirements (since the intention is to have a lightweight and usable pooling method). You could however try to implement it yourself based on the paper ( you can draw inspiration from [this post](https://discuss.pytorch.org/t/calculating-dice-coefficient/44154) for DSC with the target, in this case, being `avg_pool`.

**Comment by GF1447571253** [comment]
ok,thanks
